name: Build and Test Continoius Integration!

on:
  push:
    branches:
      - master

jobs:
   deployment:
      name: Pull the image
      runs-on: ubuntu-latest
      steps:
         - name: Pull image
           uses: actions/checkout@v3
      



  