name: Java CI with Maven

on:
  push:
    branches: 
      - development

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Dockerfile
      run: |
        version=$(mvn -q -U -Dexpression=project.version -DforceStdout maven-help-plugin:evaluate)
        version=$(echo ${version} | awk -F'.' '{print $1"."$2+1"."$3}' | sed s/[.]$//)
        echo "Current version: ${version}"
        echo "::set-output name=version::${version}"

